### PR TITLE
Made compatible with Py 3+ too but not tested

### PR DESCRIPTION
**Pull request by rautamiekka**
By using Python 3.4.2 x64's 2to3 module, converted/made compatible with Python 3+ in addition to the original 2.7+. However, workingness haven't been tested. As far as I see, there was only 1 mistake the converter made: the already-existing Py 3+ compatibility import was completely ruined, so I restored that with the original.

There's a typo in summary §Improvement string manipulation; other changes§ ...

### CODE REVIEW

**Comment by Fenixin** [comment]
Hello!

Sorry for the late answer.

Thanks for your contribution but I'm afraid that the present code is in branch beta-2-2 and master is pretty old. If you want to do that with beta-2-2 I will be glad to test and merge.

**Comment by rautamiekka** [comment]
Ok, I'll see about it. You seem to know nothing about Python 3 and/or 2-and-3 interoperability, so it's my job. I'm not perfect there either but nothing vs something is a fine line.

You really should try coding in Python 3 with what you got from Python 2.7.x and then look for cures to get it work in Python 3. If I say 90-91% of Py2 code works in 3, we should be close. I'm sure the problems will arise from either downright fatal syntax violations, or something working differently with same syntax.

The differences between 2 and 7 are rather massive as I came to learn when trying to perform this translation manually (http://getpython3.com/diveintopython3/porting-code-to-python-3-with-2to3.html was the page), so I figured I should just use the §2to3§ module and manually check for more-or-less obvious errors that introduced. The module has improved -alot- since 3 was introduced, so it might be about perfect by now, but it doesn't have the intelligence to avoid ruining some imports that were pretty tricks around the interoperability problem (you had 1 or 2 of those). It's like a bigger issue than Swedish, Norwegian and Danish have with talking to each other, like.

However, although making same script work in both versions ain't easy job, it's not impossible either, and some of the changes can be done in the beginning of the script during the "init" of the script.

**Comment by macfreek** [comment]
My advise is to write code that is syntactically compatible with both Python 2.6-2.7 and 3.2 and up. This is fairly easy. The 2to3 conversion in the commit did most of that job.

A few notes:
* No fixes in nbt are necessary. In fact, some of the changes you've made are incompatible with Python 2. E.g. to `isinstance(key, basestring):` should not be changed to `isinstance(key, str):`. This fails for unicode strings in Python 2, and Python 3 compatibility is already handled by this piece of code at top op de module:
```
try:
    unicode
    basestring
except NameError:
    unicode = str # compatibility for Python 3
    basestring = str # compatibility for Python 3
```
* Make sure to add a statements like `from __future__ import division,absolute_import,print_function,unicode_literals` at top of files. This ensures that print functions also work in Python 2.6 and up.

Last, but this is personal, I recommend to add your name to the CONTRIBUTORS.txt file, instead of the copyright statement at top of each file. This is what other contributors did.

**Comment by rautamiekka** [comment]
Hence why I said 'not tested'. There's so much code in the project too.

**Comment by Fenixin** [comment]
I will try to make region-fixer compatible with 2 and 3 for the next version. I will leave this open as a reminder and in case you end up doing some job on this.

I will try to follow all your advice, thanks!

**Comment by Fenixin** [comment]
Regionfixer is (finally) python3 compatible, closing this. Sorry for the long time it took.

**Pull request closed without merging**
