### PR TITLE
Updated world.py so that it does accept wildcards

### PR DESCRIPTION
**Pull request by Mixone-FinallyHere**

### CODE REVIEW

**Comment by Fenixin** [comment]
Hello!

Thanks for your pull request. I never thought this was needed because wildcards always worked for me. That is, worked in my linux machine and in windows with "Git Bash" terminal but I have just tried it in windows CMD and, of course, it doesn't work.

I'm not sure this ia  proper way of implementing it. Because you are not implementing all the possible wildcards, just *.mca. Do you know a why to make this work in windows?

**Comment by Mixone-FinallyHere** [comment]
Hi!

Sorry missed the message!

Well as far as I see there are a couple of options:

# "Dirty" method

Just add ifs for all possible wildcard starters

# Cleaner method

Add an argument for when the user wants to use wildcards and then have an interactive session of sorts.
So first ask for directory where files are at
And then something like "What regex do you want to use?"

With that method we directly will have a folder path to send to `scandir`, and then can just do a simple `re.match(r"REGEX", filename)` and only add those files to the list of files to scan


Of course there are even more ways to do it, but if taking into account the user base, maybe an interactive method is actually good since it will lead to less erroneous input from super long cmd line arguments

**Comment by Fenixin** [comment]
For me the best method is to make the OS work for us. Why Windows is not autocompleting the wildcard and Linux is doing it? As I said, wildcardrs work like a charm in Linux, so there must be a method to make it work in Windows.

I'm going to be very busy for two weeks or so, after that I will try to give this a look. I don't really the two methods in your comment. I tried that with the interactive mode some time ago, and it's too much work to maintain

**Comment by Fenixin** [comment]
This is fixed in master. It seems windows shell doesn't do any wildcard parsing at all. I used glob with some code to parse out world folders. Thanks for your contribution and heads-up

**Pull request closed without merging**
